### ISSUE TITLE
Documentation for pin configuration

### ISSUE THREAD

**Issue by BleuLlama** [jblang/rc9918#5]
On the main README page, you mention in section "Jumper Descriptions" that the ColecoVision is configured with J6 to the right, but in the "Port Address Jumpers" section, you mention: "For ColecoVision, you would set this to ignore (left)"

I'm pretty sure it's the latter (left) but I'm not positive which, as I don't have a ColecoVision configuration to try out. ;)

Love this card, btw. :D

**Comment by jblang** [comment]
The real ColecoVision decodes port A0-BF for the video chip, so technically, left (ignore) is the correct setting. But almost all the games use ports BE and BF so it's possible to set the jumper to the right to use tighter decoding so that only B0-BF is assigned to the video chip. Since the I/O address space can be pretty crowded on the RC2014 anyway, I normally use the right (upper half) setting and I have not come across any games that don't work with it. I will update the README to clarify this.
