### ISSUE TITLE
ym2149 jumper settings for nyan cat demo

### ISSUE THREAD

**Issue by quarterturn** [jblang/rc9918#6]
I have the nyan cat demo running on my Z180 ROMWBW "Black Adder" system but the audio from the YM2149 sounds way too low in pitch. The pace seems about right. What jumper settings on the YM2149 sound card did you use? I tried the default and the SC settings, but both work the same.

I  haven't yet tested the YM2149 board with other code, but I have tested the chip used in an Atmel setup where it plays ym stuff fine.

**Comment by jblang** [comment]
I am using the REV6 of the YM2149 board that has its own 3.58MHz clock source.  If you have REV5 or earlier, you should configure your clock divider jumpers so that you can get the clock as close to 3.58MHz as possible based on the frequency of the system clock.  The external clock divider can be set to 2 or 4, and there is a second jumper to enable the internal /2 divider on the YM2149.

Alternatively, you could remove the external clock divider jumper and the internal divider enable jumper and use a jumper wire to connect the 3.58MHz clock output of the clock input of the YM2149 (the center pin of the external clock divider jumper).

**Comment by quarterturn** [comment]
Thank you I have resolved this by making a daughterboard for my YM2149 card that contains a 3.58 MHz oscillator. It works fine now.
